

# Example Visualizations for meetup 
### by Gene Leynes

http://www.meetup.com/The-Chicago-Data-Visualization-Group/events/97690792/
## Workshop: Develop a Data App using <br>Raphael, D3, HTML and Backbone <br>(Week 3)
Date: January 28
Location: 1871

These are some example visualizations and data handling methods for discussion at the meetup.


## INITIALIZATION

```{r, cache=FALSE}
opts_chunk$set(tidy=FALSE)
```

```{r, message=FALSE, results='hide'}
source('00 Initialize.R')
```



## READ CSV AND CONVERT SOME VALUES

```{r}
rawdat = read.table(
	file = 'Database 2013-01-21 (8zQ4cW7T).csv', sep=',', quote='"', 
	flush=FALSE, header=TRUE, nrows=-1, fill=FALSE, stringsAsFactors=FALSE,
	na.strings=c('None', ''))
str(rawdat)
dat = as.data.table(rawdat)
str(dat)

## Convert booking and discharge dates to date time objects
## EXAMPLE FORMAT: 2012-12-30T20:57:19.616186
dat$booking_date = ExtractIsoTime(dat$booking_date)
dat$discharge_date_earliest = ExtractIsoTime(dat$discharge_date_earliest)

table(dat$race, useNA='ifany')

## I'm going to guess that W and WH are both "White"
dat$race = sub('^W$', 'WH', dat$race)
## I'm going to guess that B and BK are both "White"
dat$race = sub('^B$', 'BK', dat$race)

table(dat$race, useNA='ifany')

```

## VIEW SOME TABLES

```{r}
## Summary of how many unique values and missing values exist in the data
NAsummary(dat)

## More simple summaries
table(dat$gender, useNA='ifany')

## Chargs and Charges_citation are too big to print:
# table(dat$charges_citation, useNA='ifany')
# table(dat$charges, useNA='ifany')
 
## Just the top 100 charges_citation
sort(table(dat$charges_citation, useNA='ifany'), T)[1:10]
sort(table(dat$charges, useNA='ifany'), T)[1:10]

## Are the NA values really NA?
table(is.na(dat$charges))
table(is.na(dat$charges_citation))

## Write Temp File (what did you think it would do?)
# wtf(dat)

```


## SOME INITIAL PLOTS

```{r, fig.width=15}

range(dat$booking_date, na.rm=TRUE)

## Checking to see if the dates imported correctly
plot(dat$discharge_date_earliest , 1:nrow(dat))
plot(dat$booking_date , 1:nrow(dat))  ## Usually organzied by booking date?

## Not very informative, but it would let me know if the data wasn't right
plot(dat$booking_date, dat$discharge_date_earliest)


hist(dat$bail_amount, 100)
hist(pmin(dat$bail_amount, 1000000), 100)
hist(dat$age_at_booking, 100)


plot(dat$age_at_booking, dat$bail_amount, main='age by bail amount')
plot(log(bail_amount)~age_at_booking, dat, main='age by log(bail amount)')


boxplot(bail_amount~age_at_booking, dat, main='age by bail amount (much better)')
boxplot(pmin(bail_amount, 5e5)~age_at_booking, dat,
		main='age by bail amount\n(changing the limits)')
boxplot(log(bail_amount)~age_at_booking, dat, main='age by log(bail amount)')


library(mgcv)
bailbyage.gam = gam(bail_amount ~ s(age_at_booking), data=dat)
plot(bailbyage.gam, main='fitted age by bail amount')

plot(dat$age_at_booking, dat$bail_amount, 
	 main='fitted age by bail amount\n(another way)')
lines(predict(bailbyage.gam), col='red')

```

## SOME GGPLOTS

```{r, fig.width=15}
ggplot(dat, aes(x=age_at_booking, fill=factor(race))) +
	geom_density(alpha=.5) + 
	facet_grid(race ~ .)+
	xlab("Age at booking") + 
	ylab("Density by race") +
	theme(plot.title = element_text(size = 20)) +
	labs(title='Age at booking summary\nby race\n')

ggplot(dat, aes(x=bail_amount, fill=factor(race))) +
	geom_density(alpha=.5) + 
	facet_grid(race ~ .) +
	xlab("Age at booking") + 
	ylab("bail amount by race") +
	theme(plot.title = element_text(size = 20)) +
	labs(title='Bond by race summary\n')

ggplot(dat, aes(x=age_at_booking, fill=factor(gender))) +
	geom_density(alpha=.7) + 
	facet_grid(gender ~ .)+
	xlab("Age at booking") + 
	ylab("Density by race") +
	theme(plot.title = element_text(size = 20)) +
	labs(title='Age at booking summary\nby gender\n')

ggplot(dat, aes(x=age_at_booking, fill=factor(gender))) +
	geom_density(alpha=.7) + 
	facet_grid(race ~ .)+
	xlab("Age at booking") + 
	ylab("Density by race") +
	theme(plot.title = element_text(size = 20)) +
	labs(title='Age at booking summary\nby gender and race\n')

ggplot(dat, aes(x=bail_amount, fill=factor(gender))) +
	geom_density() + 
	facet_grid(gender ~ .)+
	xlab("Age at booking") + 
	ylab("bail amount by race") +
	theme(plot.title = element_text(size = 20)) +
	labs(title='Bond by race summary\n')

```






